{
  "comments": [
    {
      "key": {
        "uuid": "5a3f45e8_9c7cbc74",
        "filename": "sfc/lib/config.py",
        "patchSetId": 2
      },
      "lineNbr": 63,
      "author": {
        "id": 2091
      },
      "writtenOn": "2018-02-16T16:18:20Z",
      "side": 1,
      "message": "Any reason why adding Exception here?",
      "range": {
        "startLine": 63,
        "startChar": 15,
        "endLine": 63,
        "endChar": 24
      },
      "revId": "036944afb69463563f136f4c69d39b296e3ecea1",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5a3f45e8_3c876863",
        "filename": "sfc/lib/config.py",
        "patchSetId": 2
      },
      "lineNbr": 109,
      "author": {
        "id": 2091
      },
      "writtenOn": "2018-02-16T16:18:20Z",
      "side": 1,
      "message": "If I understood correctly, these syntax is deprectated in Python3, so why not using the one compatible with Python2 and Python3?",
      "revId": "036944afb69463563f136f4c69d39b296e3ecea1",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}