{
  "comments": [
    {
      "key": {
        "uuid": "da5c1566_d81f6408",
        "filename": "sfc/tests/functest/sfc_parent_function.py",
        "patchSetId": 7
      },
      "lineNbr": 77,
      "author": {
        "id": 6745
      },
      "writtenOn": "2018-06-12T11:31:53Z",
      "side": 1,
      "message": "Where are you catching those exceptions?",
      "range": {
        "startLine": 77,
        "startChar": 12,
        "endLine": 77,
        "endChar": 27
      },
      "revId": "37d5bca7cc52709e89d434345560cfe1d90e2e52",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}